const ROOT = 'advertisement';

export const FETCH_ADVERTISEMENT_REQUEST =  `${ROOT}/FETCH_ADVERTISEMENT_REQUEST`;
export const FETCH_ADVERTISEMENT_FAILURE = `${ROOT}/FETCH_ADVERTISEMENT_FAILURE`;
export const FETCH_ADVERTISEMENT_SUCCESS = `${ROOT}/FETCH_ADVERTISEMENT_SUCCESS`;