const ROOT = 'home';

export const FETCH_LIST_JOBS_REQUEST =  `${ROOT}/FETCH_LIST_JOBS_REQUEST`;
export const FETCH_LIST_JOBS_FAILURE = `${ROOT}/FETCH_LIST_JOBS_FAILURE`;
export const FETCH_LIST_JOBS_SUCCESS = `${ROOT}/FETCH_LIST_JOBS_SUCCESS`;

export const SET_FILTER_LIST_JOBS = `${ROOT}/SET_FILTER_LIST_JOBS`;
