const ROOT = 'home/search';

export const FETCH_LIST_LOCATION_REQUEST =  `${ROOT}/FETCH_LIST_LOCATION_REQUEST`;
export const FETCH_LIST_LOCATION_FAILURE = `${ROOT}/FETCH_LIST_LOCATION_FAILURE`;
export const FETCH_LIST_LOCATION_SUCCESS = `${ROOT}/FETCH_LIST_LOCATION_SUCCESS`;

export const HIDDEN_LIST_LOCATION = `${ROOT}/HIDDEN_LIST_LOCATION`;

